name: Convert Jupyter README

on: [push]

jobs:
  release:
    if: startsWith(github.event.head_commit.message, 'Update README')
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - uses: actions/checkout@v4
    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        conda install --yes --file requirements.txt
        pip install jupyter nbconvert tabulate pygraphviz
        pip install ".[plot]"

    - name: Convert README.ipynb
      run: |
        ls
        python docs/notebook_conversion.py
#        jupyter nbconvert --ClearMetadataPreprocessor.enabled=True --ClearOutput.enabled=True  --to markdown docs/README.ipynb --output-dir=.

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Convert README.ipynb to README.md" -a

    - name: Push changes
      if: success()
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
